name: ci
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Cache MkDocs
        uses: actions/cache@v4
        with:
          key: mkdocs-cache-${{ hashFiles('requirements.txt') }}
          path: .cache
          restore-keys: |
            mkdocs-cache-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          mkdocs build --strict
        env:
          ENABLE_PDF_EXPORT: 1

      - name: Deploy documentation
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          mkdocs gh-deploy --force --strict
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 